---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: emailsenderconfigs.konsol.sh
spec:
  group: konsol.sh
  scope: Namespaced
  names:
    plural: emailsenderconfigs
    singular: emailsenderconfig
    kind: EmailSenderConfig
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                apiTokenSecretRef:
                  type: string
                senderEmail:
                  type: string
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: emails.konsol.sh
spec:
  group: konsol.sh
  scope: Namespaced
  names:
    plural: emails
    singular: email
    kind: Email
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                senderConfigRef:
                  type: string
                recipientEmail:
                  type: string
                subject:
                  type: string
                body:
                  type: string
            status:
              type: object
              properties:
                deliveryStatus:
                  type: string
                messageId:
                  type: string
                error:
                  type: string
