---
apiVersion: konsol.sh/v1
kind: EmailSenderConfig
metadata:
  name: test-email-sender-config
  namespace: default
spec:
  apiTokenSecretRef: "email-operator"
  senderEmail: "jp@konsol.sh"
---
apiVersion: konsol.sh/v1
kind: Email
metadata:
  name: test-email
  namespace: default
spec:
  senderConfigRef: "test-email-sender-config"
  recipientEmail: "jp@konsol.sh"
  subject: "hello world!"
  body: "foo bar baz xyz!"
