---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: email-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: email-operator
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["secrets", "events"]
    verbs: ["get", "list", "watch", "create"]
  - apiGroups: ["konsol.sh"]
    resources: ["emails", "emailsenderconfigs"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: email-operator
  namespace: default
subjects:
  - kind: ServiceAccount
    name: email-operator
    namespace: default
roleRef:
  kind: ClusterRole
  name: email-operator
  apiGroup: rbac.authorization.k8s.io
